In [28]:
import pandas as pd
G=pd.read_excel('D:\Code\pycharm\AANE对比实验\补全之后的抗原距离.xlsx')
M=pd.read_excel('D:\Code\pycharm\AANE对比实验\data/titre.xlsx')
G

,virusStrain1,virusStrain2,virus_num,serum_num,distance1,antigentic1,virus_seq,serum_seq,virus_year,serum_year,distance2,antigentic,distance_pre_aane
0,A/Akita/4/1993,A/Beijing/32/1992,0,15,1.369564,0,QKLPGNDNSTATLCLGHHAVPNGTLVKTITNDQIEVTNATELVQSS...,QKLPGNDNSTATLCLGHHAVPNGTLVKTITNDQIEVTNATELVQSS...,1993,1992,1.369564,0,2.241141
1,A/Akita/4/1993,A/Beijing/353/1989,0,17,5.217231,1,QKLPGNDNSTATLCLGHHAVPNGTLVKTITNDQIEVTNATELVQSS...,QKLPGNDNSTATLCLGHHAVPNGTLVKTITNDQIEVTNATELVQSS...,1993,1989,5.217231,1,5.987188
2,A/Akita/4/1993,A/Finland/338/1995,0,88,0.294008,0,QKLPGNDNSTATLCLGHHAVPNGTLVKTITNDQIEVTNATELVQSS...,QKLPGNDNSTATLCLGHHAVPNGTLVKTITNDQIEVTNATELVQSS...,1993,1995,0.294008,0,1.354523
3,A/Akita/4/1993,A/Guangdong/25/1993,0,102,2.576925,0,QKLPGNDNSTATLCLGHHAVPNGTLVKTITNDQIEVTNATELVQSS...,QKLPGNDNSTATLCLGHHAVPNGTLVKTITNDQIEVTNATELVQSS...,1993,1993,2.576925,0,3.053351
4,A/Akita/4/1993,A/Lyon/1149/1991,0,164,8.000000,1,QKLPGNDNSTATLCLGHHAVPNGTLVKTITNDQIEVTNATELVQSS...,QKLPGNDNSTATLCLGHHAVPNGTLVKTITNDQIEVTNATELVQSS...,1993,1991,8.000000,1,8.459759
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4280,A/Wisconsin/19/2004,A/Wyoming/3/2003,390,398,1.184723,0,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,2004,2003,0.892998,0,0.410221
4281,A/Wisconsin/67/2005,A/Wisconsin/3/2007,391,392,0.331363,0,QKLPGNDDSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,2005,2007,2.000000,0,1.431881
4282,A/Wisconsin/67/2005,A/Wisconsin/68/2005,392,393,0.720329,0,QKLPGNDDSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,2005,2005,0.514573,0,1.621057
4283,A/Wisconsin/67/2005,A/Wyoming/1/2006,392,396,0.317837,0,QKLPGNDDSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,2005,2006,1.415037,0,1.610158
4284,A/Wisconsin/67/2005,A/Wyoming/3/2003,392,398,2.223170,0,QKLPGNDDSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,2005,2003,2.892998,0,3.653689

In [20]:
M['titer'] = M['titer'].str.replace('\D+', '')
M['titer']=pd.to_numeric(M['titer'], errors='coerce').fillna('0').astype('int32')
M

C:\Users\15285\AppData\Local\Temp/ipykernel_14868/2323519687.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  M['titer'] = M['titer'].str.replace('\D+', '')

,Unnamed: 0,virustrain,virus_num,serumStrain,serum_num,titer,virus_seq,serum_seq,virus_year,serum_year
0,680,A/Akita/4/1993,0,A/Beijing/32/1992,15,423,QKLPGNDNSTATLCLGHHAVPNGTLVKTITNDQIEVTNATELVQSS...,QKLPGNDNSTATLCLGHHAVPNGTLVKTITNDQIEVTNATELVQSS...,1993,1992
1,563,A/Akita/4/1993,0,A/Beijing/353/1989,17,40,QKLPGNDNSTATLCLGHHAVPNGTLVKTITNDQIEVTNATELVQSS...,QKLPGNDNSTATLCLGHHAVPNGTLVKTITNDQIEVTNATELVQSS...,1993,1989
2,980,A/Akita/4/1993,0,A/Finland/338/1995,88,960,QKLPGNDNSTATLCLGHHAVPNGTLVKTITNDQIEVTNATELVQSS...,QKLPGNDNSTATLCLGHHAVPNGTLVKTITNDQIEVTNATELVQSS...,1993,1995
3,907,A/Akita/4/1993,0,A/Guangdong/25/1993,102,240,QKLPGNDNSTATLCLGHHAVPNGTLVKTITNDQIEVTNATELVQSS...,QKLPGNDNSTATLCLGHHAVPNGTLVKTITNDQIEVTNATELVQSS...,1993,1993
4,188,A/Akita/4/1993,0,A/Lyon/1149/1991,164,10,QKLPGNDNSTATLCLGHHAVPNGTLVKTITNDQIEVTNATELVQSS...,QKLPGNDNSTATLCLGHHAVPNGTLVKTITNDQIEVTNATELVQSS...,1993,1991
...,...,...,...,...,...,...,...,...,...,...
8594,562,A/Yamagata/62/1993,401,A/Netherlands/620/1989,224,40,QKLPGNDNSTATLCLGHHAVPNGTLVKTITNDQIEVTNATELVQSS...,QKLPGNDNSTATLCLGHHAVPNGTLVKTITNDQIEVTNATELVQSS...,1993,1989
8595,906,A/Yamagata/62/1993,401,A/Shandong/9/1993,294,1120,QKLPGNDNSTATLCLGHHAVPNGTLVKTITNDQIEVTNATELVQSS...,QKLPGNDNSTATLCLGHHAVPNGTLVKTITNDQIEVTNATELVQSS...,1993,1993
8596,478,A/Yamagata/62/1993,401,A/Shanghai/11/1987,295,10,QKLPGNDNSTATLCLGHHAVPNGTLVKTITNDQIEVTNATELVQSS...,QKLPGNDNSTATLCLGHHAVPNGTLVKTITNDQIEVTNATELVQSS...,1993,1987
8597,372,A/Yamagata/62/1993,401,A/Sichuan/2/1987,299,10,QKLPGNDNSTATLCLGHHAVPNGTLVKTITNDQIEVTNATELVQSS...,QKLPGNDNSTATLCLGHHAVPNGTLVKTITNDQIEVTNATELVQSS...,1993,1987
8598,187,A/Yamagata/62/1993,401,A/Victoria/2/1990,374,40,QKLPGNDNSTATLCLGHHAVPNGTLVKTITNDQIEVTNATELVQSS...,QKLPGNDNSTATLCLGHHAVPNGTLVKTITNDQIEVTNATELVQSS...,1993,1990

In [21]:
import math
for index, row in G.iterrows():
        K=M[M['virus_num']==row['virus_num']]
        K=K[K['serum_num']==row['serum_num']].max() # tij
        S=M[M['virus_num']==row['serum_num']]
        S=S[S['serum_num']==row['serum_num']].max() # tjj
        if math.isnan(S['titer']) or math.isnan(K['titer']):
            K=M[M['virus_num']==row['virus_num']]
            K=K[K['serum_num']==row['serum_num']].max() # tji
            S=M[M['virus_num']==row['virus_num']]
            S=S[S['serum_num']==row['virus_num']].max() # tjj
        if S['titer']>K['titer']:
            G['distance2'][index]=math.log2(S['titer']/K['titer'])
        else:
            G['distance2'][index]=math.log2(K['titer']/S['titer'])

C:\Users\15285\AppData\Local\Temp/ipykernel_14868/3716413098.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  G['distance2'][index]=math.log2(S['titer']/K['titer'])
C:\Users\15285\AppData\Local\Temp/ipykernel_14868/3716413098.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  G['distance2'][index]=math.log2(K['titer']/S['titer'])

KeyboardInterrupt: