In [19]:
import numpy as np
import pandas as pd

edge=pd.read_excel('../data/distance.xlsx')
node=pd.read_excel('../data/序列数据.xlsx')
node

,viruStrain,year,seq
0,A/Akita/4/1993,1993,QKLPGNDNSTATLCLGHHAVPNGTLVKTITNDQIEVTNATELVQSS...
1,A/Alabama/5/2010,2010,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...
2,A/Alaska/5/2010,2010,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...
3,A/Algeria/G202/2009,2008,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...
4,A/Amsterdam/1609/1977,1977,QDLPGNDNSTATLCLGHHAVPNGTLVKTITNDQIEVTNATELVQSS...
...,...,...,...
397,A/Wyoming/2/2003,2003,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...
398,A/Wyoming/3/2003,2003,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...
399,A/Yamagata/56/1993,1993,QKLPGNDNSTATLCLGHHAVPNGTLVKTITNDQIEVTNATELVQSS...
400,A/Yamagata/61/1993,1993,QKLPGNDNSTATLCLGHHAVPNGTLVKTITNDQIEVTNATELVQSS...
401,A/Yamagata/62/1993,1993,QKLPGNDNSTATLCLGHHAVPNGTLVKTITNDQIEVTNATELVQSS...

In [20]:
edge

,Unnamed: 0,virusStrain1,virus_year1,virusStrain2,virus_year2,distance
0,0,A/Alabama/5/2010,2010,A/Perth/10/2010,2010,0.281468
1,1,A/Alaska/5/2010,2010,A/Guadeloupe/202/2010,2010,1.368483
2,2,A/Amsterdam/1609/1977,1977,A/Netherlands/209/1980,1980,3.250875
3,3,A/Amsterdam/1609/1977,1977,A/Rotterdam/577/1980,1980,6.000000
4,4,A/Amsterdam/1609/1977,1977,A/Netherlands/241/1982,1982,3.447832
...,...,...,...,...,...,...
1001,1001,A/Wyoming/3/2003,2003,A/Hiroshima/52/2005,2005,3.338528
1002,1002,A/Wyoming/3/2003,2003,A/Texas/40/2003,2003,0.013067
1003,1003,A/Wyoming/3/2003,2003,A/California/7/2004,2004,1.655313
1004,1004,A/Wyoming/3/2003,2003,A/Oklahoma/8/2004,2004,0.011348
1005,1005,A/Wyoming/3/2003,2003,A/Texas/6/2004,2004,1.777323

In [21]:
strain_name=list(node['viruStrain'])
seq_to_idx={strain_name:i for i,strain_name in enumerate(strain_name)}
seq_to_idx

{'A/Akita/4/1993': 0,
 'A/Alabama/5/2010': 1,
 'A/Alaska/5/2010': 2,
 'A/Algeria/G202/2009': 3,
 'A/Amsterdam/1609/1977': 4,
 'A/Anhui/1238/2005': 5,
 'A/Anhui/1239/2005': 6,
 'A/Atlanta/211/1989': 7,
 'A/Atlanta/3572/1988': 8,
 'A/Auckland/10/1997': 9,
 'A/Auckland/4382/1982': 10,
 'A/Auckland/6/2003': 11,
 'A/BadenWuerttemberg/38/2005': 12,
 'A/Bangkok/1/1979': 13,
 'A/Bangladesh/5071/2011': 14,
 'A/Beijing/32/1992': 15,
 'A/Beijing/352/1989': 16,
 'A/Beijing/353/1989': 17,
 'A/Beijing/51/2002': 18,
 'A/Bilthoven/10684/1982': 19,
 'A/Bilthoven/15793/1968': 20,
 'A/Bilthoven/16190/1968': 21,
 'A/Bilthoven/16398/1968': 22,
 'A/Bilthoven/1761/1976': 23,
 'A/Bilthoven/17938/1969': 24,
 'A/Bilthoven/1843/1975': 25,
 'A/Bilthoven/21438/1971': 26,
 'A/Bilthoven/21793/1972': 27,
 'A/Bilthoven/21801/1971': 28,
 'A/Bilthoven/2271/1976': 29,
 'A/Bilthoven/23290/1972': 30,
 'A/Bilthoven/23337/1972': 31,
 'A/Bilthoven/2600/1975': 32,
 'A/Bilthoven/2668/1970': 33,
 'A/Bilthoven/2813/1975': 34,
 'A/Bilthoven/334/1975': 35,
 'A/Bilthoven/3517/1973': 36,
 'A/Bilthoven/3895/1977': 37,
 'A/Bilthoven/4273/1975': 38,
 'A/Bilthoven/4791/1981': 39,
 'A/Bilthoven/5029/1976': 40,
 'A/Bilthoven/5146/1974': 41,
 'A/Bilthoven/5168/1976': 42,
 'A/Bilthoven/552/1973': 43,
 'A/Bilthoven/5657/1976': 44,
 'A/Bilthoven/5930/1974': 45,
 'A/Bilthoven/5931/1974': 46,
 'A/Bilthoven/6022/1972': 47,
 'A/Bilthoven/6449/1971': 48,
 'A/Bilthoven/6545/1976': 49,
 'A/Bilthoven/7398/1974': 50,
 'A/Bilthoven/748/1973': 51,
 'A/Bilthoven/808/1969': 52,
 'A/Bilthoven/908/1969': 53,
 'A/Bilthoven/93/1970': 54,
 'A/Bilthoven/9459/1974': 55,
 'A/Bratislava/31/2011': 56,
 'A/Brazil/1742/2005': 57,
 'A/Brisbane/10/2007': 58,
 'A/Brisbane/11/2010': 59,
 'A/Brisbane/24/2008': 60,
 'A/Brisbane/3/2005': 61,
 'A/Brisbane/5/2002': 62,
 'A/Brisbane/6/2002': 63,
 'A/Brisbane/7/2003': 64,
 'A/Brisbane/8/1996': 65,
 'A/Brisbane/9/2006': 66,
 'A/Caen/1/1984': 67,
 'A/California/20/2005': 68,
 'A/California/7/2004': 69,
 'A/Cameroon/675/2009': 70,
 'A/Canada/578/2004': 71,
 'A/Cheonnam/432/2002': 72,
 'A/ChristChurch/2/1988': 73,
 'A/ChristChurch/28/2003': 74,
 'A/Colorado/2/1986': 75,
 'A/Daejeon/390/2002': 76,
 'A/Durban/92/2011': 77,
 'A/Eindhoven/3447/1989': 78,
 'A/England/138/1989': 79,
 'A/England/392/2008': 80,
 'A/England/394/2008': 81,
 'A/England/42/1972': 82,
 'A/England/427/1988': 83,
 'A/England/669/2008': 84,
 'A/England/687/2008': 85,
 'A/England/7/1994': 86,
 'A/Finland/170/2003': 87,
 'A/Finland/338/1995': 88,
 'A/Finland/339/1995': 89,
 'A/Finland/381/1995': 90,
 'A/Finland/9/2008': 91,
 'A/Florida/2/2006': 92,
 'A/Florida/43/2010': 93,
 'A/Fujian/411/2002': 94,
 'A/Fujian/445/2003': 95,
 'A/Fukuoka/15/2002': 96,
 'A/Geneva/3958/1996': 97,
 'A/Geneva/5007/1989': 98,
 'A/Geneva/AI9509/1995': 99,
 'A/Guadeloupe/202/2010': 100,
 'A/Guam/228/2002': 101,
 'A/Guangdong/25/1993': 102,
 'A/Guildford/V728/1985': 103,
 'A/Guizhou/54/1989': 104,
 'A/Gunma/16/2005': 105,
 'A/Hiroshima/39/2004': 106,
 'A/Hiroshima/52/2005': 107,
 'A/HongKong/107/1971': 108,
 'A/HongKong/1/1968': 109,
 'A/HongKong/1/1989': 110,
 'A/HongKong/1/1994': 111,
 'A/HongKong/1/1997': 112,
 'A/HongKong/1550/2002': 113,
 'A/HongKong/1952/2009': 114,
 'A/HongKong/1985/2009': 115,
 'A/HongKong/20/1996': 116,
 'A/HongKong/218/2006': 117,
 'A/HongKong/2/1994': 118,
 'A/HongKong/26560/2009': 119,
 'A/HongKong/280/1997': 120,
 'A/HongKong/2831/2005': 121,
 'A/HongKong/3170/2010': 122,
 'A/HongKong/3/1995': 123,
 'A/HongKong/32/1995': 124,
 'A/HongKong/34430/2009': 125,
 'A/HongKong/357/1996': 126,
 'A/HongKong/358/1996': 127,
 'A/HongKong/38/1995': 128,
 'A/HongKong/3969/2011': 129,
 'A/HongKong/42/1996': 130,
 'A/HongKong/434/1996': 131,
 'A/HongKong/49/1995': 132,
 'A/HongKong/55/1994': 133,
 'A/HongKong/55/1995': 134,
 'A/HongKong/56/1994': 135,
 'A/HongKong/734/2001': 136,
 'A/Idaho/2008/2003': 137,
 'A/Incheon/677/2006': 138,
 'A/Iowa/19/2010': 139,
 'A/Ishikawa/102/2002': 140,
 'A/Israel/22/2009': 141,
 'A/Israel/24/2009': 142,
 'A/Israel/26/2009': 143,
 'A/Johannesburg/10/1997': 144,
 'A/Johannesburg/107/2011': 145,
 'A/Johannesburg/113/2011': 146,
 'A/Johannesburg/114/2011': 147,
 'A/Johannesburg/15/2008': 148,
 'A/Johannesburg/153/2011': 149,
 'A/Johannesburg/33/1994': 150,
 'A/Johannesburg/47/1994': 151,
 'A/Johannesburg/73/2011': 152,
 'A/Johannesburg/78/2011': 153,
 'A/Johannesburg/79/2011': 154,
 'A/Johannesburg/94/2011': 155,
 'A/Johannesburg/99/2011': 156,
 'A/Kentucky/3/2006': 157,
 'A/Kitakyushu/5/2006': 158,
 'A/Korea/770/2002': 159,
 'A/Kumamoto/102/2002': 160,
 'A/Leningrad/360/1986': 161,
 'A/Louisiana/4/2003': 162,
 'A/Lyon/108/2005': 163,
 'A/Lyon/1149/1991': 164,
 'A/Lyon/1182/1991': 165,
 'A/Lyon/1292/2006': 166,
 'A/Lyon/1313/2006': 167,
 'A/Lyon/1324/2006': 168,
 'A/Lyon/1331/2006': 169,
 'A/Lyon/1359/2006': 170,
 'A/Lyon/1381/2007': 171,
 'A/Lyon/1781/1996': 172,
 'A/Lyon/2279/1995': 173,
 'A/Lyon/2380/1981': 174,
 'A/Lyon/24222/1991': 175,
 'A/Lyon/636/2006': 176,
 'A/Lyon/672/1993': 177,
 'A/Lyon/Cx-R/3120/2009': 178,
 'A/Madrid/G102/1993': 179,
 'A/Madrid/G109/1993': 180,
 'A/Madrid/G12/1991': 181,
 'A/Madrid/G122/1993': 182,
 'A/Madrid/G130/1993': 183,
 'A/Madrid/G252/1993': 184,
 'A/Madrid/G58/1992': 185,
 'A/Malaysia/1/2004': 186,
 'A/Memphis/2/1990': 187,
 'A/Memphis/5/1990': 188,
 'A/Minnesota/17/2010': 189,
 'A/Mississippi/1/1985': 190,
 'A/Mississippi/5/2004': 191,
 'A/Montana/439520/2005': 192,
 'A/Montana/5/2011': 193,
 'A/Moscow/10/1999': 194,
 'A/Nanchang/933/1995': 195,
 'A/Nepal/1646/2004': 196,
 'A/Nepal/921/2006': 197,
 'A/Netherlands/101/1993': 198,
 'A/Netherlands/115/1993': 199,
 'A/Netherlands/118/2001': 200,
 'A/Netherlands/1/1995': 201,
 'A/Netherlands/1/2002': 202,
 'A/Netherlands/124/2001': 203,
 'A/Netherlands/126/1993': 204,
 'A/Netherlands/126/2001': 205,
 'A/Netherlands/18/1994': 206,
 'A/Netherlands/209/1980': 207,
 'A/Netherlands/22/2003': 208,
 'A/Netherlands/241/1982': 209,
 'A/Netherlands/241/1993': 210,
 'A/Netherlands/271/1995': 211,
 'A/Netherlands/300/1997': 212,
 'A/Netherlands/301/1999': 213,
 'A/Netherlands/3/1993': 214,
 'A/Netherlands/3/2000': 215,
 'A/Netherlands/330/1985': 216,
 'A/Netherlands/333/1985': 217,
 'A/Netherlands/371/1993': 218,
 'A/Netherlands/414/1998': 219,
 'A/Netherlands/427/1998': 220,
 'A/Netherlands/450/1988': 221,
 'A/Netherlands/462/1998': 222,
 'A/Netherlands/5/1998': 223,
 'A/Netherlands/620/1989': 224,
 'A/Netherlands/650/1989': 225,
 'A/Netherlands/738/1989': 226,
 'A/Netherlands/816/1991': 227,
 'A/Netherlands/823/1992': 228,
 'A/Netherlands/891/1991': 229,
 'A/Netherlands/91/1996': 230,
 'A/Netherlands/935/1992': 231,
 'A/Netherlands/938/1992': 232,
 'A/Nevada/5/2007': 233,
 'A/NewCaledonia/20/2003': 234,
 'A/NewCaledonia/6/2002': 235,
 'A/NewYork/55/2004': 236,
 'A/Nice/491/1997': 237,
 'A/Nijmegen/3126/1992': 238,
 'A/Nijmegen/3129/1992': 239,
 'A/NordrheinWestfalen/1/2010': 240,
 'A/NorthCarolina/13/2005': 241,
 'A/NorthDakota/1/2004': 242,
 'A/Norway/1/2009': 243,
 'A/Norway/1762/2011': 244,
 'A/Norway/1775/2011': 245,
 'A/Norway/3789/2009': 246,
 'A/Norway/3790/2009': 247,
 'A/Okayama/29/2005': 248,
 'A/Oklahoma/5/1988': 249,
 'A/Oklahoma/8/2004': 250,
 'A/Osaka/56/2004': 251,
 'A/Oslo/13676/1983': 252,
 'A/Oslo/21/1997': 253,
 'A/Oslo/2352/1993': 254,
 'A/Oslo/244/1997': 255,
 'A/Oviedo/31/1992': 256,
 'A/Panama/2007/1999': 257,
 'A/Paris/207/2002': 258,
 'A/Paris/320/1992': 259,
 'A/Paris/325/1992': 260,
 'A/Paris/407/1992': 261,
 'A/Paris/424/1992': 262,
 'A/Paris/457/1992': 263,
 'A/Paris/458/2008': 264,
 'A/Paris/467/1992': 265,
 'A/Paris/490/1992': 266,
 'A/Paris/512/1992': 267,
 'A/Paris/548/1992': 268,
 'A/Paris/564/1992': 269,
 'A/Paris/583/1992': 270,
 'A/Paris/597/1992': 271,
 'A/Paris/614/1992': 272,
 'A/Perth/10/2010': 273,
 'A/Perth/16/2009': 274,
 'A/Peru/1296/2004': 275,
 'A/Philippines/1159050/2002': 276,
 'A/Philippines/2191/2009': 277,
 'A/Philippines/2/1982': 278,
 'A/Philippines/472/2002': 279,
 'A/Philippines/825/2003': 280,
 'A/Poitiers/1341/2008': 281,
 'A/PortChalmers/1/1973': 282,
 'A/Pusan/504/2002': 283,
 'A/RhodeIsland/1/2010': 284,
 'A/Romania/802-03/2003': 285,
 'A/Rotterdam/577/1980': 286,
 'A/Rotterdam/5828/1977': 287,
 'A/Rotterdam/8179/1977': 288,
 'A/Sakai/20/2011': 289,
 'A/Sendai/C273/1992': 290,
 'A/Seoul/1/1990': 291,
 'A/Seoul/4436/2008': 292,
 'A/Serres/77/2007': 293,
 'A/Shandong/9/1993': 294,
 'A/Shanghai/11/1987': 295,
 'A/Shanghai/24/1990': 296,
 'A/Shanghai/369/2003': 297,
 'A/Shiga/6/1993': 298,
 'A/Sichuan/2/1987': 299,
 'A/Singapore/1/1996': 300,
 'A/Singapore/15/2001': 301,
 'A/Singapore/34/1989': 302,
 'A/Singapore/35/1989': 303,
 'A/Singapore/35/2005': 304,
 'A/Singapore/36/1989': 305,
 'A/Singapore/36/2004': 306,
 'A/Singapore/37/2004': 307,
 'A/Singapore/38/2005': 308,
 'A/Singapore/40/1989': 309,
 'A/Singapore/53/1989': 310,
 'A/Singapore/57/2006': 311,
 'A/Singapore/70/2005': 312,
 'A/Singapore/95/2003': 313,
 'A/Singapore/N593/2008': 314,
 'A/Sofia/141/2003': 315,
 'A/Sofia/319/2007': 316,
 'A/SouthAustralia/102/2001': 317,
 'A/SouthAustralia/15/1994': 318,
 'A/SouthAustralia/23/1992': 319,
 'A/SouthAustralia/25/1994': 320,
 'A/SouthAustralia/27/1992': 321,
 'A/SouthAustralia/3/2011': 322,
 'A/SouthAustralia/8/1992': 323,
 'A/Stockholm/10/1985': 324,
 'A/Stockholm/112/2009': 325,
 'A/Stockholm/1/2010': 326,
 'A/Stockholm/12/1988': 327,
 'A/Stockholm/12/1992': 328,
 'A/Stockholm/13/1992': 329,
 'A/Stockholm/18/2011': 330,
 'A/Stockholm/20/1991': 331,
 'A/Stockholm/20/1993': 332,
 'A/Stockholm/2/2010': 333,
 'A/Stockholm/26/2008': 334,
 'A/Stockholm/7/1992': 335,
 'A/Stockholm/8/1992': 336,
 'A/Stockholm/89/2009': 337,
 'A/Sweden/2/2009': 338,
 'A/Sweden/3/2008': 339,
 'A/Switzerland/1397477/2008': 340,
 'A/Switzerland/1409281/2008': 341,
 'A/Sydney/5/1997': 342,
 'A/Taiwan/1529/2003': 343,
 'A/Taiwan/51/2005': 344,
 'A/Taiwan/760/2007': 345,
 'A/Taiwan/8/2002': 346,
 'A/Taiwan/83/2006': 347,
 'A/Taiwan/99/2006': 348,
 'A/Tanger/533/2009': 349,
 'A/Tennessee/6/2004': 350,
 'A/Texas/1/1977': 351,
 'A/Texas/37/2007': 352,
 'A/Texas/40/2003': 353,
 'A/Texas/6/2004': 354,
 'A/Tilburg/5957/1992': 355,
 'A/Torino/14/2008': 356,
 'A/Toulon/1244/2006': 357,
 'A/Toulouse/878/2001': 358,
 'A/Townsville/1/2003': 359,
 'A/Trieste/25c/2007': 360,
 'A/Ukraine/13/2006': 361,
 'A/Ulaanbaatar/3849/2010': 362,
 'A/Umea/2000/1992': 363,
 'A/Umea/4/2009': 364,
 'A/Uppsala/3/2011': 365,
 'A/Uruguay/716/2007': 366,
 'A/Uvurkhangai/3970/2010': 367,
 'A/Victoria/102/2003': 368,
 'A/Victoria/110/2004': 369,
 'A/Victoria/1/1988': 370,
 'A/Victoria/1/1989': 371,
 'A/Victoria/208/2009': 372,
 'A/Victoria/210/2009': 373,
 'A/Victoria/2/1990': 374,
 'A/Victoria/3/1975': 375,
 'A/Victoria/33/1992': 376,
 'A/Victoria/500/2004': 377,
 'A/Victoria/503/2006': 378,
 'A/Victoria/523/2004': 379,
 'A/Victoria/7/1987': 380,
 'A/Victoria/75/1995': 381,
 'A/Waikato/1/1989': 382,
 'A/Washington/1/2004': 383,
 'A/Wellington/1/2004': 384,
 'A/Wellington/3/1990': 385,
 'A/Wellington/4/1985': 386,
 'A/Wellington/5/1989': 387,
 'A/Wisconsin/13/2010': 388,
 'A/Wisconsin/15/2009': 389,
 'A/Wisconsin/19/2004': 390,
 'A/Wisconsin/3/2007': 391,
 'A/Wisconsin/67/2005': 392,
 'A/Wisconsin/68/2005': 393,
 'A/Wuhan/359/1995': 394,
 'A/Wyoming/0049/2005': 395,
 'A/Wyoming/1/2006': 396,
 'A/Wyoming/2/2003': 397,
 'A/Wyoming/3/2003': 398,
 'A/Yamagata/56/1993': 399,
 'A/Yamagata/61/1993': 400,
 'A/Yamagata/62/1993': 401}

In [22]:
# seq=name.join(seq)
node=node.reset_index()
con1=pd.merge(edge,node,left_on='virusStrain1',right_on='viruStrain')
con1=con1.reset_index()
con1

,level_0,Unnamed: 0,virusStrain1,virus_year1,virusStrain2,virus_year2,distance,index,viruStrain,year,seq
0,0,0,A/Alabama/5/2010,2010,A/Perth/10/2010,2010,0.281468,1,A/Alabama/5/2010,2010,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...
1,1,1,A/Alaska/5/2010,2010,A/Guadeloupe/202/2010,2010,1.368483,2,A/Alaska/5/2010,2010,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...
2,2,2,A/Amsterdam/1609/1977,1977,A/Netherlands/209/1980,1980,3.250875,4,A/Amsterdam/1609/1977,1977,QDLPGNDNSTATLCLGHHAVPNGTLVKTITNDQIEVTNATELVQSS...
3,3,3,A/Amsterdam/1609/1977,1977,A/Rotterdam/577/1980,1980,6.000000,4,A/Amsterdam/1609/1977,1977,QDLPGNDNSTATLCLGHHAVPNGTLVKTITNDQIEVTNATELVQSS...
4,4,4,A/Amsterdam/1609/1977,1977,A/Netherlands/241/1982,1982,3.447832,4,A/Amsterdam/1609/1977,1977,QDLPGNDNSTATLCLGHHAVPNGTLVKTITNDQIEVTNATELVQSS...
...,...,...,...,...,...,...,...,...,...,...,...
1001,1001,1001,A/Wyoming/3/2003,2003,A/Hiroshima/52/2005,2005,3.338528,398,A/Wyoming/3/2003,2003,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...
1002,1002,1002,A/Wyoming/3/2003,2003,A/Texas/40/2003,2003,0.013067,398,A/Wyoming/3/2003,2003,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...
1003,1003,1003,A/Wyoming/3/2003,2003,A/California/7/2004,2004,1.655313,398,A/Wyoming/3/2003,2003,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...
1004,1004,1004,A/Wyoming/3/2003,2003,A/Oklahoma/8/2004,2004,0.011348,398,A/Wyoming/3/2003,2003,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...
1005,1005,1005,A/Wyoming/3/2003,2003,A/Texas/6/2004,2004,1.777323,398,A/Wyoming/3/2003,2003,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...

In [23]:
con2=pd.merge(con1,node,left_on='virusStrain2',right_on='viruStrain')

con2=pd.concat([con2,pd.DataFrame(columns=['indexon'])])
con2

,level_0,Unnamed: 0,virusStrain1,virus_year1,virusStrain2,virus_year2,distance,index_x,viruStrain_x,year_x,seq_x,index_y,viruStrain_y,year_y,seq_y,indexon
0,0.0,0.0,A/Alabama/5/2010,2010.0,A/Perth/10/2010,2010.0,0.281468,1.0,A/Alabama/5/2010,2010.0,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,273.0,A/Perth/10/2010,2010.0,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,NaN
1,125.0,125.0,A/Brisbane/10/2007,2007.0,A/Perth/10/2010,2010.0,3.574253,58.0,A/Brisbane/10/2007,2007.0,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,273.0,A/Perth/10/2010,2010.0,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,NaN
2,564.0,564.0,A/Perth/16/2009,2009.0,A/Perth/10/2010,2010.0,0.528977,274.0,A/Perth/16/2009,2009.0,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,273.0,A/Perth/10/2010,2010.0,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,NaN
3,625.0,625.0,A/RhodeIsland/1/2010,2010.0,A/Perth/10/2010,2010.0,0.997591,284.0,A/RhodeIsland/1/2010,2010.0,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,273.0,A/Perth/10/2010,2010.0,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,NaN
4,777.0,777.0,A/Uruguay/716/2007,2007.0,A/Perth/10/2010,2010.0,5.253897,366.0,A/Uruguay/716/2007,2007.0,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,273.0,A/Perth/10/2010,2010.0,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1001,917.0,917.0,A/Wisconsin/67/2005,2005.0,A/Brisbane/10/2007,2007.0,0.236558,392.0,A/Wisconsin/67/2005,2005.0,QKLPGNDDSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,58.0,A/Brisbane/10/2007,2007.0,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,NaN
1002,915.0,915.0,A/Wisconsin/67/2005,2005.0,A/Trieste/25c/2007,2007.0,0.351098,392.0,A/Wisconsin/67/2005,2005.0,QKLPGNDDSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,360.0,A/Trieste/25c/2007,2007.0,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,NaN
1003,926.0,926.0,A/Wisconsin/67/2005,2005.0,A/Anhui/1238/2005,2005.0,1.408939,392.0,A/Wisconsin/67/2005,2005.0,QKLPGNDDSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,5.0,A/Anhui/1238/2005,2005.0,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,NaN
1004,928.0,928.0,A/Wisconsin/67/2005,2005.0,A/Lyon/636/2006,2006.0,1.095445,392.0,A/Wisconsin/67/2005,2005.0,QKLPGNDDSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,176.0,A/Lyon/636/2006,2006.0,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,NaN
1005,930.0,930.0,A/Wisconsin/67/2005,2005.0,A/Lyon/1331/2006,2006.0,1.066587,392.0,A/Wisconsin/67/2005,2005.0,QKLPGNDDSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,169.0,A/Lyon/1331/2006,2006.0,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,NaN

In [24]:
con2.rename(columns={'viruStrain_x':'virustrain','index_x':'virus_num','index_y':'serum_num','seq_x':'virus_seq','seq_y':'serum_seq','year_x':'virus_year','year_y':'serum_year'},inplace=True)
con2

,level_0,Unnamed: 0,virusStrain1,virus_year1,virusStrain2,virus_year2,distance,virus_num,virustrain,virus_year,virus_seq,serum_num,viruStrain_y,serum_year,serum_seq,indexon
0,0.0,0.0,A/Alabama/5/2010,2010.0,A/Perth/10/2010,2010.0,0.281468,1.0,A/Alabama/5/2010,2010.0,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,273.0,A/Perth/10/2010,2010.0,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,NaN
1,125.0,125.0,A/Brisbane/10/2007,2007.0,A/Perth/10/2010,2010.0,3.574253,58.0,A/Brisbane/10/2007,2007.0,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,273.0,A/Perth/10/2010,2010.0,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,NaN
2,564.0,564.0,A/Perth/16/2009,2009.0,A/Perth/10/2010,2010.0,0.528977,274.0,A/Perth/16/2009,2009.0,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,273.0,A/Perth/10/2010,2010.0,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,NaN
3,625.0,625.0,A/RhodeIsland/1/2010,2010.0,A/Perth/10/2010,2010.0,0.997591,284.0,A/RhodeIsland/1/2010,2010.0,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,273.0,A/Perth/10/2010,2010.0,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,NaN
4,777.0,777.0,A/Uruguay/716/2007,2007.0,A/Perth/10/2010,2010.0,5.253897,366.0,A/Uruguay/716/2007,2007.0,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,273.0,A/Perth/10/2010,2010.0,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1001,917.0,917.0,A/Wisconsin/67/2005,2005.0,A/Brisbane/10/2007,2007.0,0.236558,392.0,A/Wisconsin/67/2005,2005.0,QKLPGNDDSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,58.0,A/Brisbane/10/2007,2007.0,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,NaN
1002,915.0,915.0,A/Wisconsin/67/2005,2005.0,A/Trieste/25c/2007,2007.0,0.351098,392.0,A/Wisconsin/67/2005,2005.0,QKLPGNDDSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,360.0,A/Trieste/25c/2007,2007.0,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,NaN
1003,926.0,926.0,A/Wisconsin/67/2005,2005.0,A/Anhui/1238/2005,2005.0,1.408939,392.0,A/Wisconsin/67/2005,2005.0,QKLPGNDDSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,5.0,A/Anhui/1238/2005,2005.0,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,NaN
1004,928.0,928.0,A/Wisconsin/67/2005,2005.0,A/Lyon/636/2006,2006.0,1.095445,392.0,A/Wisconsin/67/2005,2005.0,QKLPGNDDSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,176.0,A/Lyon/636/2006,2006.0,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,NaN
1005,930.0,930.0,A/Wisconsin/67/2005,2005.0,A/Lyon/1331/2006,2006.0,1.066587,392.0,A/Wisconsin/67/2005,2005.0,QKLPGNDDSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,169.0,A/Lyon/1331/2006,2006.0,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,NaN

In [27]:
distance=con2[['virusStrain1','virus_num','virusStrain2','serum_num','distance','virus_seq','serum_seq','virus_year','serum_year']]

In [28]:
distance

,virusStrain1,virus_num,virusStrain2,serum_num,distance,virus_seq,serum_seq,virus_year,serum_year
0,A/Alabama/5/2010,1.0,A/Perth/10/2010,273.0,0.281468,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,2010.0,2010.0
1,A/Brisbane/10/2007,58.0,A/Perth/10/2010,273.0,3.574253,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,2007.0,2010.0
2,A/Perth/16/2009,274.0,A/Perth/10/2010,273.0,0.528977,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,2009.0,2010.0
3,A/RhodeIsland/1/2010,284.0,A/Perth/10/2010,273.0,0.997591,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,2010.0,2010.0
4,A/Uruguay/716/2007,366.0,A/Perth/10/2010,273.0,5.253897,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,2007.0,2010.0
...,...,...,...,...,...,...,...,...,...
1001,A/Wisconsin/67/2005,392.0,A/Brisbane/10/2007,58.0,0.236558,QKLPGNDDSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,2005.0,2007.0
1002,A/Wisconsin/67/2005,392.0,A/Trieste/25c/2007,360.0,0.351098,QKLPGNDDSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,2005.0,2007.0
1003,A/Wisconsin/67/2005,392.0,A/Anhui/1238/2005,5.0,1.408939,QKLPGNDDSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,2005.0,2005.0
1004,A/Wisconsin/67/2005,392.0,A/Lyon/636/2006,176.0,1.095445,QKLPGNDDSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,2005.0,2006.0
1005,A/Wisconsin/67/2005,392.0,A/Lyon/1331/2006,169.0,1.066587,QKLPGNDDSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,QKLPGNDNSTATLCLGHHAVPNGTIVKTITNDQIEVTNATELVQSS...,2005.0,2006.0

In [29]:
titer=distance[['virus_num','serum_num','distance']]
titer['distance'].replace('<', '',inplace=True, regex=True)
titer.to_excel('distance_graph.xls')

C:\Users\15285\AppData\Local\Temp/ipykernel_14684/864537630.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  titer['distance'].replace('<', '',inplace=True, regex=True)
C:\Users\15285\AppData\Local\Temp/ipykernel_14684/864537630.py:3: FutureWarning: As the xlwt package is no longer maintained, the xlwt engine will be removed in a future version of pandas. This is the only engine in pandas that supports writing in the xls format. Install openpyxl and write to an xlsx file instead. You can set the option io.excel.xls.writer to 'xlwt' to silence this warning. While this option is deprecated and will also raise a warning, it can be globally set and the warning suppressed.
  titer.to_excel('distance_graph.xls')

In [30]:
titer

      virus_num  serum_num  distance
0           1.0      273.0  0.281468
1          58.0      273.0  3.574253
2         274.0      273.0  0.528977
3         284.0      273.0  0.997591
4         366.0      273.0  5.253897
...         ...        ...       ...
1001      392.0       58.0  0.236558
1002      392.0      360.0  0.351098
1003      392.0        5.0  1.408939
1004      392.0      176.0  1.095445
1005      392.0      169.0  1.066587

[1006 rows x 3 columns]

In [31]:
titer['sum']=titer['virus_num']+titer['serum_num']
titer

C:\Users\15285\AppData\Local\Temp/ipykernel_14684/4231688617.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  titer['sum']=titer['virus_num']+titer['serum_num']

      virus_num  serum_num  distance    sum
0           1.0      273.0  0.281468  274.0
1          58.0      273.0  3.574253  331.0
2         274.0      273.0  0.528977  547.0
3         284.0      273.0  0.997591  557.0
4         366.0      273.0  5.253897  639.0
...         ...        ...       ...    ...
1001      392.0       58.0  0.236558  450.0
1002      392.0      360.0  0.351098  752.0
1003      392.0        5.0  1.408939  397.0
1004      392.0      176.0  1.095445  568.0
1005      392.0      169.0  1.066587  561.0

[1006 rows x 4 columns]

In [14]:
import csv

A = []
for i in node['seq']:
  a = (" ".join(i))
  A.append(a)
df = pd.DataFrame({'sequence':A})
df.to_csv('test.txt',index=0,header=0,quoting=csv.QUOTE_NONE)

In [15]:
sp=pd.read_csv('test.txt',sep=' ',header=None)
sp

,0,1,2,3,4,5,6,7,8,9,...,319,320,321,322,323,324,325,326,327,328
0,Q,K,L,P,G,N,D,N,S,T,...,M,R,N,V,P,E,K,Q,T,R
1,Q,K,L,P,G,N,D,N,S,T,...,M,R,N,V,P,E,K,Q,T,R
2,Q,K,L,P,G,N,D,N,S,T,...,M,R,N,V,P,E,K,Q,T,R
3,Q,K,L,P,G,N,D,N,S,T,...,M,R,N,V,P,E,K,Q,T,R
4,Q,D,L,P,G,N,D,N,S,T,...,M,R,N,V,P,E,K,Q,T,R
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
397,Q,K,L,P,G,N,D,N,S,T,...,M,R,N,V,P,E,K,Q,T,R
398,Q,K,L,P,G,N,D,N,S,T,...,M,R,N,V,P,E,K,Q,T,R
399,Q,K,L,P,G,N,D,N,S,T,...,M,R,N,V,P,E,K,Q,T,R
400,Q,K,L,P,G,N,D,N,S,T,...,M,R,N,V,P,E,K,Q,T,R
401,Q,K,L,P,G,N,D,N,S,T,...,M,R,N,V,P,E,K,Q,T,R

In [16]:
sp=sp.replace('S',15)
sp=sp.replace('T',16)
sp=sp.replace('N',11)
sp=sp.replace('G',5)
sp=sp.replace('L',9)
sp=sp.replace('I',7)
sp=sp.replace('V',17)
sp=sp.replace('P',12)
sp=sp.replace('R',14)
sp=sp.replace('K',8)
sp=sp.replace('D',2)
sp=sp.replace('A',0)
sp=sp.replace('Y',19)
sp=sp.replace('Q',13)
sp=sp.replace('E',3)
sp=sp.replace('F',4)
sp=sp.replace('C',1)
sp=sp.replace('H',6)
sp=sp.replace('W',18)
sp=sp.replace('M',10)
sp

,0,1,2,3,4,5,6,7,8,9,...,319,320,321,322,323,324,325,326,327,328
0,13,8,9,12,5,11,2,11,15,16,...,10,14,11,17,12,3,8,13,16,14
1,13,8,9,12,5,11,2,11,15,16,...,10,14,11,17,12,3,8,13,16,14
2,13,8,9,12,5,11,2,11,15,16,...,10,14,11,17,12,3,8,13,16,14
3,13,8,9,12,5,11,2,11,15,16,...,10,14,11,17,12,3,8,13,16,14
4,13,2,9,12,5,11,2,11,15,16,...,10,14,11,17,12,3,8,13,16,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
397,13,8,9,12,5,11,2,11,15,16,...,10,14,11,17,12,3,8,13,16,14
398,13,8,9,12,5,11,2,11,15,16,...,10,14,11,17,12,3,8,13,16,14
399,13,8,9,12,5,11,2,11,15,16,...,10,14,11,17,12,3,8,13,16,14
400,13,8,9,12,5,11,2,11,15,16,...,10,14,11,17,12,3,8,13,16,14
401,13,8,9,12,5,11,2,11,15,16,...,10,14,11,17,12,3,8,13,16,14

In [17]:
sp.to_excel('map_idx.xlsx')